### PR TITLE
Fix QR code rendering

### LINKED ISSUE #307: QR code does not display the correct address (mixing up)
The QR code component is not properly rendering the associated address

### PR DESCRIPTION
**Pull request by nop33**
Close #307

### CODE REVIEW

File: src/components/Buttons/QRCodeButton.tsx [hunk 1]
```diff
@@ -30,8 +30,8 @@ interface QRCodeButtonProps {
 
 const QRCodeButton = ({ textToEncode, className }: QRCodeButtonProps) => (
   <>
-    <QRCodeIcon className={className} data-tip data-for="qr-code-tooltip" data-event="click" size={15} />
-    <Tooltip id="qr-code-tooltip" backgroundColor="black" globalEventOff="click" place="right">
+    <QRCodeIcon className={className} data-tip data-for={`qr-${textToEncode}`} data-event="click" size={15} />
+    <Tooltip id={`qr-${textToEncode}`} backgroundColor="black" globalEventOff="click" place="right">
```
Comment (LeeAlephium) [inline src/components/Buttons/QRCodeButton.tsx:34]: Nit: I suppose you could DRY this but eh, up to you

**Review by LeeAlephium — APPROVED** [review]
Sanity check passed on my end, addresses are associated properly :pinata:

File: src/components/Buttons/QRCodeButton.tsx (hunk 1 above)
Comment (nop33) [reply src/components/Buttons/QRCodeButton.tsx]: Fixed :)
