### PR TITLE
[v2.0] Fix swap tx display

### LINKED ISSUE #603: Fix display of swap transaction
I used the DEX to swap `0.1` TBTC for `15.95` ALPH.

The pending tx display as well as the confirmed one display wrong values.

Problems with the pending tx row:
- Wrong displayed destination address
- Wrong displayed amounts

image

Problems with confirmed tx row:
- Wrong displayed TBTC amount

image

See related transaction: https://explorer.testnet.alephium.org/transactions/d62b41a05d57d2b59d098e1bcf6eeac4daa265fda4a8ff86451ff49b7e958f56

### PR DESCRIPTION
**Pull request by nop33**
Closes #603 

image

image

image

### CODE REVIEW

File: src/types/transactions.ts [hunk 1]
```diff
@@ -149,3 +148,7 @@ export type CsvExportTimerangeQueryParams = {
 export type CsvExportQueryParams = CsvExportTimerangeQueryParams & {
   addressHash: AddressHash
 }
+
+// TODO: Transfer to SDK
+export type TransactionDirection = 'in' | 'out' | 'swap'
+export type TransactionInfoType = TransactionDirection | 'move' | 'pending'
```
Comment (nop33) [inline src/types/transactions.ts:154]: Will be removed once https://github.com/alephium/js-sdk/pull/149 is merged and published

Comment (nop33) [reply src/types/transactions.ts]: @mvaivre Done! Ready for review :)
